trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  rm: rm554113
  location: eastus
  resourceGroup: rg-smartoothai
  service-plan: smartoothAi
  app-name: smartooth-Ai-$(rm)
  runtime: JAVA:17-java17
  sku: F1
  nome_artefato: smartoothai

stages:
  - stage: criarInfra
    jobs:
      - job: criaWebApp
        displayName: 'Criar Serviço de Aplicativo'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'MyAzureSubscription'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create --location $(location) --name $(resourceGroup)
                az appservice plan create -g $(resourceGroup) -n $(service-plan) --is-linux
                az webapp create -g $(resourceGroup) -p $(service-plan) -n $(app-name) --runtime "$(runtime)"
              displayName: 'Criar Infraestrutura'

  - stage: BuildApp
    jobs:
      - job: buildApp
        displayName: 'Build do App Java'
        steps:
          - task: Gradle@3
            displayName: 'Compilar aplicação com Gradle'
            inputs:
              gradleWrapperFile: 'gradlew'
              tasks: 'build'
              jdkVersionOption: 1.17

          - task: CopyFiles@2
            displayName: 'Copiar .jar para staging'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/smartoothai/build/libs'
              Contents: 'SmartoothAI-0.0.1.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/$(nome_artefato)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publicar artefato'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(nome_artefato)'
              ArtifactName: '$(nome_artefato)'

  - stage: deployApp
    jobs:
      - job: deployWebApp
        displayName: 'Deploy no Azure WebApp'
        steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Baixar artefato do build'
            inputs:
              buildType: 'current'
              downloadType: 'specific'
              artifactName: '$(nome_artefato)'
              downloadPath: '$(System.DefaultWorkingDirectory)'

          - script: |
              echo "Arquivos do artefato baixado:"
              ls -R $(System.DefaultWorkingDirectory)/$(nome_artefato)
            displayName: 'Listar arquivos baixados'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Realizar deploy do .jar'
            inputs:
              azureSubscription: 'MyAzureSubscription'
              appType: 'webAppLinux'
              WebAppName: '$(app-name)'
              packageForLinux: '$(System.DefaultWorkingDirectory)/$(nome_artefato)/SmartoothAI-0.0.1.jar'